# Generated by Django 5.0.4 on 2024-04-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_remove_product_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='productpicture',
            name='back_view',
            field=models.ImageField(blank=True, upload_to='product_images/', verbose_name='Back View'),
        ),
        migrations.AlterField(
            model_name='productpicture',
            name='front_view',
            field=models.ImageField(blank=True, upload_to='product_images/', verbose_name='Front View'),
        ),
        migrations.AlterField(
            model_name='productpicture',
            name='side_view',
            field=models.ImageField(blank=True, upload_to='product_images/', verbose_name='Side View'),
        ),
    ]
