# Generated by Django 5.0.4 on 2024-04-21 12:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_product_stock_order_closed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_veryfied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='owner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
