# Generated by Django 5.0.4 on 2024-04-21 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_product_is_veryfied_product_owner_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_veryfied',
            new_name='is_verified',
        ),
    ]
